In [1]:
from portana.data import simulated

In [2]:
connection = simulated.SimConnection()
connection.set_asset_type(simulated.EquityAssetType())

In [3]:
security1 = connection.get_security('1233541', ('2019-01-01', '2019-12-31'))
security2 = connection.get_security('1233544', ('2018-11-01', '2019-11-30'))
index1 = connection.get_security('213154', ('2018-11-01', '2019-11-30'))

In [4]:
security1.timeseries

                 Price  Total Return Index
2019-01-01  924.093614          100.000000
2019-01-02  845.102444           91.914047
2019-01-03  918.546539          100.326539
2019-01-04  864.300773           94.865163
2019-01-05  917.404540          101.132088
...                ...                 ...
2019-12-27  513.673706          293.516820
2019-12-28  480.613144          275.981852
2019-12-29  460.257747          265.568260
2019-12-30  492.300863          285.284055
2019-12-31  487.920513          284.063718

[365 rows x 2 columns]

In [5]:
from portana.analyzer import equity_analyzer

In [6]:
analyzer = equity_analyzer.EquityAnalyzer()

In [7]:
analyzer.add_security(security1)
analyzer.add_security(security2)
analyzer.set_comp_index(index1)

In [12]:
analyzer.get_sharpes('tr', 252, 0.02)

(             1233541   1233544
 2019-11-30  2.379685  2.896877,
               213154
 2019-11-30  3.813402)

In [99]:
rets = analyzer.get_returns('px')[0].results
vols = analyzer.get_volatilities('px', 252)[0].results

In [101]:
rets[[-1]] / vols

array([[-0.54182885,  0.28664494]])

In [79]:
analyzer._price_series

               1233541     1233544
2019-01-01  924.093614  241.977253
2019-01-02  845.102444  242.336860
2019-01-03  918.546539  242.850152
2019-01-04  864.300773  242.110289
2019-01-05  917.404540  240.420740
...                ...         ...
2019-11-26  538.795586  247.606951
2019-11-27  516.360286  249.152274
2019-11-28  557.354951  251.399224
2019-11-29  543.506173  253.747763
2019-11-30  552.497764  255.457013

[334 rows x 2 columns]

In [83]:
a

array([[0.04668092, 0.01222391]])

In [65]:
import numpy as np
results = np.expand_dims(analyzer.get_betas('tr')[0].results, axis=0)
date = analyzer.get_betas('tr')[0].dates
col_name = analyzer.get_betas('tr')[0].col_names

array([[-0.03805943, -0.00413079]])

In [67]:
import pandas as pd

pd.DataFrame(data=results)

0         1
0 -0.038059 -0.004131

In [29]:
res

array(0.00144003)

In [30]:
np.var(index_rets.results.copy())

0.0014357088119221534

In [29]:
import numpy as np
np.var(a, axis=0)

8107.078045338583

In [12]:
analyzer.comp_index.timeseries.prices

array([794.62610205, 715.96352893, 711.06400591, 700.10042843,
       697.43174497, 692.69471555, 665.88112608, 660.92106378,
       609.12352676, 556.42070761, 541.51203762, 554.66186966,
       545.30474409, 547.55257424, 522.11613077, 521.62196733,
       503.07012936, 501.16310103, 486.95156052, 489.18762804,
       485.2333908 , 472.667198  , 485.39991497, 481.72316944,
       479.45861372, 450.28112645, 440.10501766, 454.61191743,
       460.34500982, 448.93471533, 454.58415613, 421.76219427,
       399.36450209, 424.32485425, 421.95563392, 423.60666536,
       412.63856883, 396.91259101, 397.43983208, 377.03232644,
       355.40191906, 347.33966474, 344.52950992, 356.26526479,
       374.81388661, 363.94339903, 377.27367088, 366.42337451,
       371.18585927, 384.75364207, 388.21138161, 397.0923367 ,
       419.29010959, 442.03933695, 387.87833256, 377.13597073,
       384.24937106, 382.16182618, 372.86213687, 358.00929051,
       355.79277152, 363.20571966, 383.90917392, 380.59

In [56]:
import numpy as np
np.cumprod(a, axis=0)

array([[1000.        , 1000.        ],
       [ 914.52038046, 1001.48611924],
       [ 993.99728021, 1003.60735949],
       [ 935.29568831, 1000.5497863 ],
       [ 992.76147526,  993.56752281],
       [ 979.88212707, 1004.00223167],
       [1058.73335787, 1021.74196297],
       [1070.10388918, 1015.2382031 ],
       [1062.98698773, 1005.13241757],
       [1033.93170229, 1009.45422311],
       [1108.44961266, 1001.31282845],
       [1068.92893213,  988.26282629],
       [1023.09342728,  983.11755636],
       [ 996.8779934 ,  983.77867194],
       [ 961.96866886, 1018.56186951],
       [ 933.05835553, 1035.99931464],
       [ 950.68823593, 1028.26613268],
       [ 909.77353946, 1039.08084072],
       [ 860.72948369, 1051.30934308],
       [ 836.30281588, 1053.31096043],
       [ 866.36546739, 1052.63104006],
       [ 902.61006654, 1047.34616409],
       [ 904.27295003, 1040.55778678],
       [ 878.56151714, 1025.13402073],
       [ 954.08327623, 1034.64805787],
       [ 974.02559224, 10

In [31]:
a = analyzer.get_returns('px').results

In [37]:
a[1:]

array([[ 8.69055534e-02,  2.11809251e-03],
       [-5.90560891e-02, -3.04658307e-03],
       [ 6.14413043e-02, -6.97842685e-03],
       [-1.29732554e-02,  1.05022644e-02],
       [ 8.04701184e-02,  1.76690158e-02],
       [ 1.07397497e-02, -6.36536436e-03],
       [-6.65066404e-03, -9.95410289e-03],
       [-2.73336229e-02,  4.29973749e-03],
       [ 7.20723721e-02, -8.06514497e-03],
       [-3.56540163e-02, -1.30328922e-02],
       [-4.28798431e-02, -5.20637810e-03],
       [-2.56236949e-02,  6.72468490e-04],
       [-3.50186530e-02,  3.53567307e-02],
       [-3.00532796e-02,  1.71196720e-02],
       [ 1.88947243e-02, -7.46446629e-03],
       [-4.30369231e-02,  1.05174212e-02],
       [-5.39079822e-02,  1.17685765e-02],
       [-2.83790300e-02,  1.90392805e-03],
       [ 3.59470887e-02, -6.45507729e-04],
       [ 4.18352306e-02, -5.02063475e-03],
       [ 1.84230549e-03, -6.48150300e-03],
       [-2.84332655e-02, -1.48225944e-02],
       [ 8.59606955e-02,  9.28077398e-03],
       [ 2.

In [34]:
a

array([[ 1.00000000e+00,  1.00000000e+00],
       [ 8.69055534e-02,  2.11809251e-03],
       [-5.90560891e-02, -3.04658307e-03],
       [ 6.14413043e-02, -6.97842685e-03],
       [-1.29732554e-02,  1.05022644e-02],
       [ 8.04701184e-02,  1.76690158e-02],
       [ 1.07397497e-02, -6.36536436e-03],
       [-6.65066404e-03, -9.95410289e-03],
       [-2.73336229e-02,  4.29973749e-03],
       [ 7.20723721e-02, -8.06514497e-03],
       [-3.56540163e-02, -1.30328922e-02],
       [-4.28798431e-02, -5.20637810e-03],
       [-2.56236949e-02,  6.72468490e-04],
       [-3.50186530e-02,  3.53567307e-02],
       [-3.00532796e-02,  1.71196720e-02],
       [ 1.88947243e-02, -7.46446629e-03],
       [-4.30369231e-02,  1.05174212e-02],
       [-5.39079822e-02,  1.17685765e-02],
       [-2.83790300e-02,  1.90392805e-03],
       [ 3.59470887e-02, -6.45507729e-04],
       [ 4.18352306e-02, -5.02063475e-03],
       [ 1.84230549e-03, -6.48150300e-03],
       [-2.84332655e-02, -1.48225944e-02],
       [ 8.

In [28]:
import numpy as np
res = (np.diff(a, axis=0) / a[:-1])
res

array([-8.08595314e-02,  9.15256416e-02, -5.44360009e-02,  6.60613924e-02,
       -8.35316726e-03,  8.50902066e-02,  1.53598379e-02, -2.03057588e-03,
       -2.27135347e-02,  7.66924603e-02, -3.10339281e-02, -3.82597549e-02,
       -2.10036068e-02, -3.03985648e-02, -2.54331914e-02,  2.35148125e-02,
       -3.84168349e-02, -4.92878940e-02, -2.37589418e-02,  4.05671769e-02,
        4.64553188e-02,  6.46239365e-03, -2.38131774e-02,  9.05807837e-02,
        2.55221588e-02,  3.93368234e-02, -1.22769490e-02, -1.78019270e-02,
       -4.75015351e-02,  2.96741229e-02, -2.28477076e-02,  4.40282875e-02,
        5.97096915e-02,  3.17443922e-02, -6.44749313e-03,  1.78105420e-02,
       -1.02283350e-03, -8.90037999e-02,  6.78819385e-02,  1.04050781e-02,
        9.93563243e-02,  4.79891954e-02,  1.92533295e-04,  3.03748460e-02,
        4.83407414e-02,  2.07684500e-02,  1.57167314e-03,  2.16152361e-02,
       -4.58759421e-03, -2.64698896e-02, -5.08268684e-02,  4.64704945e-03,
        3.00182741e-02,  

In [22]:
test_series = analyzer._tot_ret_idx_series

In [26]:
import numpy as np
match = test_series.dates == np.datetime64('2019-01-01')

In [29]:
test_series.results[match]

array([[100.        , 106.71259666]])

In [69]:
import numpy as np

test_array = np.ndarray((len(dates),2))
test_array[:,0] = security1.timeseries[start:end].prices

In [71]:
array = ['foo', 'bar']

In [73]:
for idx, i in enumerate(array):
    print(idx, i)

0 foo
1 bar


In [77]:
security1.isin

'1233541'

3
